# Auto-bottler for FreeCAD Homebrew Formulae
#
# This travis config first builds a homebrew bottle for each formula and macOS combintation, stages them to 
# BinTray and ultimately deploys the collection to Bintray
#
# Based on prior art here - https://gist.github.com/maelvalais/068af21911c7debc4655cdaa41bbf092

#language: cpp
language: ruby
os: osx

osx_image:
  - xcode9.2
  - xcode9.4

env:
  global:
  - BT_USER=bblacey  # BT_KEY must be set at REPO level
  - TAP_BOTTLE_ROOT_URL=https://dl.bintray.com/bblacey/bottles-freecad
  - HOMEBREW_BINTRAY_USER=${BT_USER}
  - HOMEBREW_BINTRAY_KEY=${BT_KEY}
  - HOMEBREW_NO_AUTO_UPDATE=yes
  - HOMEBREW_LOGS=/tmp
  matrix:
  - FORMULA=coin
  - FORMULA=matplotlib
  - FORMULA=med-file
  - FORMULA=nglib
  - FORMULA=opencamlib
  - FORMULA=pivy
  - FORMULA=pyside2
  - FORMULA=pyside2-tools
  - FORMULA=qtwebkit
  - FORMULA=shiboken2

# Lay down a fresh Homebrew install
before_install:
  - mkdir ~/usr_local && sudo mv /usr/local/* ~/usr_local
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - travis_retry brew install libyaml gmp openssl@1.1 openssl jq

# Install the travis-compatible test-bot
install:
  - brew tap maelvalais/test-bot
  - mkdir -p $(brew --repo $TRAVIS_REPO_SLUG)
  - rm -rf $(brew --repo $TRAVIS_REPO_SLUG)
  - ln -s $PWD $(brew --repo $TRAVIS_REPO_SLUG)
  - git fetch --unshallow || true
  - export HOMBREW_DEVELOPER=1
  - #HOMEBREW_DEVELOPER=1 brew doctor

before_script:
  - sed -i '' "s:TRAVIS_BUILD_NUMBER:$TRAVIS_BUILD_NUMBER:g" .bintray-staging.json

script:
    #- |
    #if [[ $TRAVIS_EVENT_TYPE =~ cron|api ]]; then
    #  brew install ${FORMULA}.rb && brew test ${FORMULA}.rb && brew linkage --test ${FORMULA}.rb || exit 123
    #fi
    #if [[ $TRAVIS_EVENT_TYPE =~ pull_request ]]; then
    #  brew test-bot --root-url=$TAP_BOTTLE_ROOT_URL
    #fi
  #- brew test-bot --root-url=$TAP_BOTTLE_ROOT_URL
  - brew test-bot --root-url=$TAP_BOTTLE_ROOT_URL Formula/${FORMULA}.rb
  - ls *.bottle*.* || echo "==> No bottle created here"

# Upload the bottle to staging area for this build
after_script: true
  #curl -T ${FORUMULA}-*bottle*.{tar.gz,json} https://api.bintray.com/content/$BT_USER/

jobs:
  include:
  - stage: deploy
    name: "Publish bottles"
    os: linux
    env: OS=any_linux

    # Download the staged bottles and publish to Bintray
    script:
    - |
      bottleArtifacts=$(curl -u${BT_USER}:${BT_KEY} https://api.bintray.com/packages/${BT_USER}/travis-staging/bottles/versions/${TRAVIS_BUILD_NUMBER}/files?include_unpublished=1 | jq -r '.[].path')
      echo "Staged bottles artifacts: ${bottleArtifacts}"
      for stagedArtifact in ${bottleArtifacts}; do
         echo "Downloading unpublished staged bottling artifact $stagedArtifact"
         travis_retry curl -LO -u${BT_USER}:${BT_KEY} https://dl.bintray.com/${BT_USER}/travis-staging/$stagedArtifact;
      done
    - |
      if ls *.{json,tar.gz}; then
        sed -i 's:/usr/local:/home/linuxbrew/.linuxbrew:g' *.json;
        #brew test-bot --ci-upload --root-url=$TAP_BOTTLE_ROOT_URL --git-name=${BT_USER} --git-email=bruce@blacey.com --bintray-org=$TAP_BOTTLE_ORG --verbose;
        brew test-bot --ci-upload --root-url=https://dl.bintray.com/bblacey/homebrew-freecad --bintray-org=bblacey --verbose;
      else
        echo "==> No staged bottless, skipping --ci-upload";
      fi

    before_install:
    - umask 022 && chmod 0644 Formula/*.rb
    - export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
    - yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" || (brew update --force)
    - sudo rm -f /home/travis/.phpenv/shims/php-config /opt/pyenv/shims/*-config /usr/local/clang-*/bin/llvm-config

    before_script:
    - sed -i "s:TRAVIS_BUILD_NUMBER:$TRAVIS_BUILD_NUMBER:g" .bintray-staging.json

    # Removed staged bottles from Bintray for this build version
    after_script:
    - rm *.{json,tar.gz}
    - curl -X DELETE -u$BT_USER:$BT_KEY https://api.bintray.com/packages/$BT_USER/travis-staging/bottles/$TRAVIS_BUILD_NUMBER

deploy:
  provider: bintray
  file: ".bintray-staging.json"
  user: ${BT_USER}
  on:
    all_branches: true
    #condition: os = osx
  skip_cleanup: true
  key: ${BT_KEY}
