language: cpp
os: osx

osx_image: 
  - xcode9.2
  - xcode9.4

env:
  global:
  - HOMEBREW_NO_AUTO_UPDATE=yes
  - HOMEBREW_LOGS=/tmp
  matrix:
    - FORMULA=med-file
    - FORMULA=nglib
#    - FORMULA=coin
#    - FORMULA=matplotlib
#    - FORMULA=med-file
#    - FORMULA=nglib
#    - FORMULA=pivy
#    - FORMULA=pyside2
#    - FORMULA=pyside2-tools
#    - FORMULA=qtwebkit
#    - FORMULA=shiboken2
#    - FORMULA=opencamlib

script:
   - echo "Bottling $FORMULA"
   - sw_vers

jobs:
   include:
     - stage: deploy
       name: "Publish bottles"
       script: echo "Publishing bottles"
